### ISSUE TITLE
Sometimes results are not returned by the bot on Slack

### ISSUE THREAD

**Issue by nicholasamorim** [nzlosh/err-stackstorm#20]
err-stackstorm version: latest
st2 version: 3.0.0

This seems to happen with a specific action/alias.

Alias:

```yaml
name: "control_service"
action_ref: "bot.control_system_services_dev"
description: "Controls a service on dev"
formats:
  - "{{operation=restart}} {{name}} on dev"
result:
  # Before it was format: "done" and it still didn't work
  format: "operation completed {~} {{ execution.result }}"
```

The above works when an operation _fails_. Never when successfull. ST2 does report `chatops.post_result` being sent in _both_ outcomes.

The action itself is a vanilla `local-shell-cmd`.

```yaml
# A generic action to run the SM2 deploy scripts.
# Note that this is only necessary because ST2's aliases
# do not support static parameters. see st2 #1704
---
name: control_system_services_dev
description: Control dev system services
runner_type: local-shell-cmd
entry_point: ""
enabled: true
parameters:
  timeout:
    type: integer
    immutable: false
    default: 30
  sudo:
    description: "Run command with sudo"
    type: boolean
    immutable: true
    default: true
  kwarg_op:
    immutable: true
  cmd:
    description: "Command to run"
    type: string
    immutable: true
    default: "service {{name}} {{operation}}"
  operation:
    description: "start|stop|restart"
    type: string
    required: true
    default: "dev"
    immutable: false # blocking accidental usage to prod
  name:
    description: "service name"
    type: string
    required: true
```

It might be related to `local-shell-cmd` runner. I have an alias directly invoking `core.remote` and the output works just fine:

```yaml
---
name: "remote_shell_cmd"
action_ref: "core.remote"
description: "Execute a command on a remote host via SSH."
formats:
  - "run {{cmd}} on {{hosts}}"
result:
   format: |
      Ran command *{{execution.parameters.cmd}}* on *{{ execution.result | length }}* hosts.

      {% for host in execution.result %}
      \*Host\*: {{host}} {{ ":white_check_mark:" if execution.result[host].stdout else ":x:" }}
      \`\`\`{{ execution.result[host].stdout or execution.result[host].stderr or "No result"}}\`\`\`
      {% endfor %}
```
