### ISSUE TITLE
Stackstorm action notification not sent to errbot/mattermost

### ISSUE THREAD

**Issue by lenba** [nzlosh/err-stackstorm#7]
I have configured errbot and I can see that commands listed in !st2help return results, but when I try to create a notification after an action using ActionChain workflows, the message is not sent to errbot.

Following the examples for setting up ActionChain:

https://docs.stackstorm.com/actionchain.html

I have set up: chains/echochain.yaml

```
---
# Action definition metadata
name: "echochain"
description: "Simple Action Chain workflow"

# `runner_type` has value `action-chain` to identify that action is an ActionChain.
runner_type: "action-chain"

# `entry_point` path to the ActionChain definition file, relative to the pack's action directory.
entry_point: "chains/echochain.yaml"

enabled: true
parameters:
  skip_notify:
    default:
      - c2
notify:
  on-complete:
    message: "\"@lenba: Action succeeded.\""
    routes:
      - "errbot"
```
And chains/echochain.yaml

```
---
    chain:
	-
            name: "c1"
            ref: "core.local"
            parameters:
                cmd: "echo c1"
            on-success: "c2"
            on-failure: "c4"
        -
            name: "c2"
            ref: "core.local"
            parameters:
                cmd: "echo \"c2: parent exec is {{action_context.parent.execution_id}}.\""
            on-success: "c3"
            on-failure: "c4"
        -
            name: "c3"
            ref: "core.local"
            parameters:
                cmd: "echo c3"
            on-failure: "c4"
        -
            name: "c4"
            ref: "core.local"
            parameters:
                cmd: "echo fail c4"
    default: "c1"
```

**Comment by nzlosh** [comment]
After going over the StackStorm documentation I realised that you can provide a `data` key in the notification section.
```
notify:
  on-complete:
    message: "\"@lenba: Action succeeded.\""
    routes:
      - "errbot"
    data:
      source_channel: "#channel"
      user: "@user"
```
I just tested this and it worked for me.
